### ISSUE TITLE
Demo Content Sub-Module

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/og#102]
I'm experimenting with a submodule that adds some demo content to help someone new to OG better understand how it works. 

I have to have an initial PR ready in a day or two. Not sure if this is necessary or helpful, but I'd like to try it anyway and see what folks think.

**Comment by stpaultim** [comment]
OK, I've pushed a first draft PR with some silly content. I will probably work on the actual content a little more later and am open to suggestions. 

My PR adds two sub-modules, because if I combine the config files into the same module as the code generating the content nodes, it breaks. 

I am able to create the group nodes in the same module as the config files, but not the group content nodes. I would love idea on how to get these things working together to remove the need for two modules. 

* og_demo_config
* og_demo_content

You must enable the config module first. 

One solution would be to create the content types using php, but I'm interested in experimenting with and learning more about what we can and can't do with config files (recipes). It could be there there is a bug that needs fixing.

**Comment by argiepiano** [comment]
@stpaultim I've looked at the PR and tried combining both into a single one. It worked! Two important things:

1. You must invoke `entity_property_info_cache_clear()` before creating any content in the hook_install() implementation. This will force Entity Plus to create the appropriate metadata for the new fields.
2. You need to include a .module file - otherwise the module doesn't show up in the installer UI

A few additional suggestions/questions:
- Creating a view of all groups and including a link in the main menu
- Once you open a group, showing a block that displays all the content for that group (you'll need to depend on og_context)
- And, more ambitious, creating a user that has access to some groups and can only see those. For this you'll need og_access and ALSO will need to trigger a node access permission rebuild (with `node_access_rebuild()`)

So, this will provide a good sample of some basic possibilities of OG. What do you think? I can help...

**Comment by stpaultim** [comment]
Thanks @argiepiano 

I had tried invoking cach_clear_all, but that wasn't enough. I was unaware of entity_property_info_cache_clear. I'm glad that works. 

I did have a .module file, because I am aware of that requirement and because it worked locally. I suspect that git did not commit that, because it was empty. Maybe I need to add an opening <?php statement so that it registers.

I like your other ideas and will see what I can do on my own, but I may need help along the way.

**Comment by stpaultim** [comment]
OK, I merged the two modules back into one and added the .module file. I have not yet started working on the new features.

**Comment by stpaultim** [comment]
@argiepiano - I've done the first two things on your list, but am not sure if I'll get to the third tonight. 

It's all pretty ugly so far, but functional. 

I recommend that we merge an early version of this ASAP. We can make it better in a follow-up PR. 

Getting this into the module is going to make it MUCH easier for others to help test the module and find bugs. The sooner we get some version of this in, the better. We can then get input on how to make it better.

**Comment by stpaultim** [comment]
@argiepiano - I just hit a blocker that might require your assistance. 

It seems that my demo content module is not generating roles and permissions for the group content type. I have found that when I create new content types and designate them as a groups, roles and permissions are generated in the database. 

These roles and permissions were not generated for the content type "Group".  This content type was generated by simply uploading a config file. How do we trigger creation of these roles and permissions?

**Comment by stpaultim** [comment]
@argiepiano - Didn't find any problems with your update. 

I merged your changes into my PR so that I could try 1-2 more small things. 

Mostly, I just made one group into a private group, so there would be some difference between what an admin sees and an unauthenticated user sees. See this commit:
https://github.com/backdrop-contrib/og/pull/105/commits/4a2dfc567510fc56ec920f514a4af5d45f13d7f9

I think tried rebuilding permissions, but I'm not sure this is doing what I wanted. 
https://github.com/backdrop-contrib/og/pull/105/commits/9778fa539eed304f37bdb379facbae7bbda0b1f4

Anytime you are happy with this. I suggest we merge it in and then make improvements later. 

I do plan to create BETTER content, but I don't think that should be a blocker. Any content will be helpful to folks testing the module and might encourage more folks to test it. We can update the content in a future PR.

**Comment by argiepiano** [comment]
@stpaultim your latest commits do a few things that are problematic. It may be that you are working with a stale branch, and I'm seeing a few "reverts" of things that previous merges had changed:

- It reverts already-merged changes to og's core views: og_members_admin, og_all_user_group_content
- It re-adds file og.views_default.inc, which was eliminated in a previous merge. 

Or perhaps you are working with a branch from my own repository that may be stale? Instead of cloning my branch, try starting from a clean 1.x-2.x branch, and then apply my PR #105  using the `patch` linux command. Or rebase your branch to the current version of branch 1.x-2.x

Once you are able to do that I can review the permission rebuild to see if it's working correctly. 

While you are there, can you please add a README.md that explains what this module does? 

Thanks!

**Comment by argiepiano** [comment]
Hi @stpaultim. I see you pushed commits again, but the problems are still there. If you click on "Files changed" in your PR you'll see (e.g. at the bottom, see attached snapshot) that if I ever merge this PR it will revert changes that were merged in the last few days. Can you please check on this again?

For example, this was a PR submitted by VasasA that got merged three day ago. Your current PR, as you see below, would undo this.
 
<img width="924" alt="Screen Shot 2022-05-23 at 2 17 58 PM" src="https://user-images.githubusercontent.com/9938978/169899341-e03a36c0-e300-41da-a70c-762d2ad05454.png">

**Comment by stpaultim** [comment]
Well, I pushed my changes and they should not be any different than yours. BUT, I also could see the difference in the diff file. I don't know why. 

So, instead I just made a small PR against your PR. You can accept it or deny it.

I figured out the problem with the permissions rebuild. It does seem to be working correctly, it was confusion on my part.

The only thing this PR does is hide the Core Developer group from the public, just so that the list of groups appears different from the admin user to the public.

**Comment by stpaultim** [comment]
OK, now I think I understand what the problem was. I misinterpreted your original concern. 

I think I should have done a rebase of my branch and that would have solved it. Although there are still things that confuse me about the diff file I was being shown for that PR.

**Comment by argiepiano** [comment]
Thank you, @stpaultim!
