### ISSUE TITLE
OG views are all missing

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/og#16]
On the OG settings page `admin/config/group/settings`, there is a list to select "the View that should be used to show and control the people in the group". As far as I know, it should be the view `og_members_admin` but it isn't available in the list. Instead, the `comments_recent` view is selected (that's just the first view in alphabetical order).

Not sure, but I guess the mentioned view is defined in https://github.com/laryn/og/blob/1.x-2.x/og_ui/includes/views/og_ui.views_default.inc.

**Comment by laryn** [comment]
All views seem to be missing... Anyone up for doing a basic D7 install, upgrading to Backdrop, and exporting the views? Unless you know of a better/quicker way... :)

**Comment by VasasA** [comment]
@laryn Download the [exported views](https://drive.google.com/file/d/1DHYvctxB0-RLC45JShInLeg3iKE50fst/view?usp=sharing).
I followed the official [upgrading description](https://api.backdropcms.org/documentation/upgrading-from-drupal-7), but I encountered two problems:
- **OG views are stored in code**, you can manually edit and save each view to **put its data back into the D7 database** ( step 2.5.1 in the upgrading description):
  1. Open the page of views in D7: admin/structure/views
  2. Use the "Edit" link and press the "Save" button at all of the OG views (5 pieces)
  3. Check the "views_view" table in the database of D7: there are 5 new records of OG views.

- **entity_ui and entity_plus modules don't exist in D7**:
  1. Run the `update.php` according to step 3.7 in the upgrading description. It shows an error message (Fatal error: Class EntityPlusDefaultViewsController...), but it is an unmissable step, because the update.php refreshes the 'system' table.
  2. Run this SQL command (enable the modules): `UPDATE 'system' SET 'status'=1 WHERE 'name' = 'entity_ui' OR 'name' = 'entity_plus'`
  3. Run the `update.php` again.
  4. Follow the upgrading description.

**Comment by laryn** [comment]
@VasasA Awesome, thanks! I recall a similar problem with Ubercart (in terms of Entity Plus and Entity UI not existing for Drupal 7) and @bugfolder created a few stub modules that can be installed on the D7 site before dumping the database so they are enabled by default. I should have thought of that earlier.

https://github.com/backdrop-contrib/ubercart/wiki/Upgrading-Ubercart-from-Drupal-7

I'll try to get these Views in place today or tomorrow -- unless you or @stpaultim want to make a PR, feel free. Just post here if you're doing it so we don't both do it (I'll do the same).

**Comment by laryn** [comment]
I've imported these Views and it seems like maybe something was lost in translation -- perhaps because the Views are set up as "Content pane" displays which I don't think exists in Backdrop. But I can spot check and recreate/reconnect bits as needed, I think.

**Comment by laryn** [comment]
Going to add these to the module for now, and may need to adjust for VBO on the one view later (see #22 )

**Comment by laryn** [comment]
Thanks for your help @olafgrabienski and @VasasA !

**Comment by olafgrabienski** [comment]
@laryn Thank you! First, after updating my test site with the latest code, the view still wasn't available. But after uninstalling OG, deleting some config files and installing the module again, there were several OG views including `og_members_admin` which appeared on the settings page.

Unfortunately, something went wrong during the uninstall / reinstall process: I got the following message on `admin/modules/list/confirm`:

> FieldException: Attempted to create an instance of field og_membership_request, but that field does not exist. in field_create_instance() (line 515 of .../core/modules/field/field.crud.inc).

Do you have an idea how to recreate the mentioned field for my test site?

**Comment by laryn** [comment]
@olafgrabienski I experienced something similar and ended up dumping the database completely, clearing out the config directory, and reinstalling from scratch. Then I filed this to make sure we didn't forget to clean up the uninstall process:
https://github.com/backdrop-contrib/og/issues/23
