### ISSUE TITLE
Views / Bulk Operations missing

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/og#22]
I'm looking into the Views and it seems the Bulk Operations aren't showing up in Backdrop. (Maybe it's looking for a `vbo` module in the code -- which is in core, I think?).

![Screen Shot 2020-11-17 at 7 45 43 PM](https://user-images.githubusercontent.com/871421/99472173-b2711080-290d-11eb-9719-6c9cae373b87.jpg)

**Comment by laryn** [comment]
[Posted to Zulip](https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/VBO):
> How do I add a new `$type` to Backdrop's simplified VBO system? I am looking at OG right now and it looks like the bulk actions are there and are using `hook_action_info` correctly, but the type is `og_membership` (for example) rather than any of the core options. They aren't showing up in Views.

**Comment by laryn** [comment]
This is relevant from @jenlampton regarding this issue:

> There is a work-around that core is using for this (see the user delete action). Essentially the "action" becomes a redirect to a form, passing data via the the SESSION, and then performs the actual action in the submit handler.

**Comment by argiepiano** [comment]
Has this been addressed? Just for fun some time ago I started porting VBO and noticed that D7's and B's actions are not compatible. Since VBO relies on actions, the porting is much more difficult. 

I think it'd easier to create "backdrop flavor" actions for OG than porting VBO. There were talks about potentially hiring to complete this port https://forum.backdropcms.org/forum/organic-groups-module-backdrop @irinaz .

If this is still on the table, I have some "freer" time in May and I could help. In the meantime I'm helping ("cause it's fun") fixing some of the other issues in the OG queue.

**Comment by argiepiano** [comment]
Now that all tests are passing, I'm interested in solving this issue and will start working on it slowly (in case someone wants to compare notes or help).

I have two options: I can create a solution specific for OG that uses the current Backdrop bulk action workflow and add custom forms to the bulk process to capture any required information (e.g. selecting which role you want to apply to all selected users in the View). The other option is more comprehensive and involves modifying the current Backdrop bulk actions functionality to take it closer to what VBO looked like. The latter may be helpful in the long run for other modules, and to add configurable actions to core that were removed in the past.   

I think I'll start with option no. 1 first, as it will be quicker and simpler, and perhaps tackle 2 in the future.

**Comment by laryn** [comment]
@argiepiano Fully support! I'll assign to you to take over on this one.

**Comment by argiepiano** [comment]
PR #83 ready for testing.

**Comment by argiepiano** [comment]
IMPORTANT: in order to test on an existing site you need to manually modify the view og_members_admin (OG members admin) and add the Bulk Operation:

1. Add "OG membership from User account" in Relationships

<img width="693" alt="Screen Shot 2022-04-29 at 4 51 25 PM" src="https://user-images.githubusercontent.com/9938978/166078178-1d539038-e98b-449f-9f50-c61d8126f135.png">

2. Add the Bulk Operations "OG membership: Bulk operations" and be sure to SELECT the relationship "OG membership from user" in the Relationship dropdown.

<img width="664" alt="Screen Shot 2022-04-29 at 4 51 18 PM" src="https://user-images.githubusercontent.com/9938978/166078185-b1b29a3a-acaa-42a8-a4d8-41827e2d7d37.png">

**Comment by olafgrabienski** [comment]
Many thanks for the PR! I've applied it on my test site, and it works nicely on a group's *People* page like `group/node/123/admin/people`.

Notes:

- In my `og_members_admin` view, the "OG membership from User account" relationship was already present.
- All existing actions work: Modify membership status, Modify OG user roles (Add roles / Remove roles), Remove from group
- Question: are there other Views with Bulk operations in Organic Groups?

**Comment by argiepiano** [comment]
Great! Thanks for testing. I looked at the other OG views that are defined by the module itself and couldn't find any other uses of Bulk Operations. I looked in the D7 version too.

**Comment by argiepiano** [comment]
I believe this may be ready to merge?

I ported Views Bulk Operations over the weekend, but since OG makes such light use of Bulk Operations, I think this PR (which uses core's Bulk Operations) should suffice, rather than creating a new dependency on VBO.

**Comment by olafgrabienski** [comment]
Not having another dependency would be great, at least from my site-builder perspective. @laryn What do you think about it?

**Comment by laryn** [comment]
Merging on faith since we don't even have an alpha release of OG yet. Thanks @argiepiano for the PR and @olafgrabienski for testing!
