### ISSUE TITLE
Notice: Undefined index: target_type / target_bundles

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/og#24]
After adding a content type "Group" on `admin/structure/types/add`, I saw these notices in DBlog:

- Notice: Undefined index: target_type in og_ui_form_node_type_form_submit() (line 992 of [...]/modules/og/og_ui/og_ui.module)
- Notice: Undefined index: target_bundles in og_ui_form_node_type_form_submit() (line 993 of [...]/modules/og/og_ui/og_ui.module)

Strangely, after adding *another* content type for Groups on the same site, there were no notices.

Is it possible that the notice appeared because I tried to set the content type to "Group content" before I had a "Group" type?

**Comment by indigoxela** [comment]
I can confirm that - the nagging stops after the first group got created.

**Comment by argiepiano** [comment]
This issue happens because, when there are no available og target types or target bundles (i.e. when none have been defined yet), `$form['og']['target_type']` and ` $form['og']['target_bundles']` are not set in `og_ui_form_node_type_form_alter()`. The submit handler tries to access those values, and thus the notice is thrown. 

Also, this notice is thrown regardless of the content type you create or edit (e.g. try to edit the Page content type), provided that no target types or bundles have been defined.

**Comment by argiepiano** [comment]
PR #60

**Comment by olafgrabienski** [comment]
@argiepiano - many thanks for the PR! I've applied it on a test site, works for me - the notices don't appear anymore.

(Tested both, adding a Group content type and editing a the Page content type.)
