### ISSUE TITLE
Get tests working

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/og#32]
Getting the tests ported and working would be a big help in navigating what is and isn't working. 

@docwilmot indicated that he may have a go at getting that functional. 👏

**Comment by stpaultim** [comment]
@docwilmot mentioned today that he started on this and that it was a big task. 

I would think that fixing some tests would be easier than others. Is this something that someone like myself could jump in and find specific tests that seem fixable and write a PR specific for those test WITHOUT stepping on the toes of what someone else might be doing?

If I were to do this, I suppose I would open a ticket for whichever test I thought I might be able to resolve and submit a PR. Maybe I would also put a note here to let folks know what I'm doing?

Or is it best that one person handle this as one task?

**Comment by laryn** [comment]
I've merged all PRs related to tests to date but they aren't green yet.
https://github.com/backdrop-contrib/og/runs/5337433365?check_suite_focus=true

**Comment by indigoxela** [comment]
Hi @laryn I started to work on this, an initial PR is available, but there are still some pretty "juicy" failures to fix.

Like `Cannot access protected property SelectQuery::$alterMetaData` :fearful:

**Comment by indigoxela** [comment]
Very slow progress and currently I'm not sure if there will be any more - I'm not familiar with the original og module code and not familiar at all with entity_plus.

**Comment by olafgrabienski** [comment]
> Very slow progress and currently I'm not sure if there will be any more ...

Many thanks however for working on the tests! Hope you don't have to give up, and maybe somebody else can chime in?

**Comment by docwilmot** [comment]
I'm suspecting that the test code may be more the source of its errors than the actual module. The D7 OG tests used Entity API's test entities and `entity_feature` modules, which dont exist in Backdrop. So I attempted to convert the D7 test entity. But the OG API for attaching and referencing is a bit complex so pretty sure my test entities may be lacking properties that might cause them not to respond to testing as expected. Even if the module itself works fine with real entities.

**Comment by indigoxela** [comment]
> I'm suspecting that the test code may be more the source of its errors than the actual module.

Yes, a significant part of failing tests should be fixable in the tests. My current approach is to get those "out of the way", so we can figure out actually broken functionality in a second step. But that's also a bit tricky.

**Comment by indigoxela** [comment]
I'd suggest to make an intermediate merge now, before the PR gets too big. All tests complete (yay!) - many still failing (meh), but things are already a lot better.

For the next steps: is anyone here an expert (or at least more familiar) with EntityFieldQuery?

**Comment by laryn** [comment]
Merged this as an "intermediate merge" that moves us forward. Thanks @indigoxela! 
_(Reopening this issue)_

**Comment by indigoxela** [comment]
@laryn unfortunately that PR contained a breaking change - which I discovered today. See #51 for details and PR.

**Comment by indigoxela** [comment]
Now for the "juicy" part `Cannot access protected property SelectQuery::$alterMetaData`

Here's the related core issue: https://github.com/backdrop/backdrop-issues/issues/5582

**Comment by indigoxela** [comment]
Another step forward: https://github.com/backdrop-contrib/og/pull/55

**Comment by laryn** [comment]
Merged the next step. Re opening this issue.

**Comment by indigoxela** [comment]
Oh dear, I lost patience with this miserable stub entity type "og_entity_test". Only switching to "node" gets the OgUiUserPermissionsTestCase working.

The problem was that with the stub type no admin pages (like /admin/config/group/permissions/ENTITY_TYPE/BUNDLE) get created, which was the reason for the failures.

**Comment by indigoxela** [comment]
I think I'm done with #58 - probably all tests that aren't related to actually broken functionality should be fixed now.

And probably I can't do much anymore. I'm absolutely not familiar with D7 Entity API nor with Entity Plus.

Some notes: Submodule og_access seems severely broken, probably because of glitches in the way the membership gets added (or should I say - does not get added) to group content.

Membership entity cache does not work at all - I'm also not familiar with how that all works or should work in core.

However, I was able to reduce the "nagging log" of functional tests a lot. May now the force be with someone else. :crossed_fingers:

**Comment by argiepiano** [comment]
Hi everyone. I got to work a bit on some of the tests today - I was careful to work on things others above have not worked on, using the latest dev with all the merges. Tonight I got all tests in class `OgUiManagePeopleTestCase` working (changes needed were minimal)

Please let me know if you prefer for me to open a different issue. For now I'll link my PR to this issue, but I can remove it if you prefer.  

PR #61 

All tests inside that class are now passing 🎉

**Comment by indigoxela** [comment]
> Tonight I got all tests in class OgUiManagePeopleTestCase working

Brilliant! Another step forward.

**Comment by argiepiano** [comment]
Hey @indigoxela ,

> I think I'm done with #58 - probably all tests that aren't related to actually broken functionality should be fixed now.

I see that #58 focuses on `OgUiUserPermissionsTestCase`. I wanted to give that one a try with the original code (with `og_entity_test`) to see if I can make that work (wish me luck!). But I don't want to step on any toes - so I thought I'd check you are cool with that. 



> Membership entity cache does not work at all - I'm also not familiar with how that all works or should work in core.

I see a problematic line in `og_entity_info()` - `    'entity cache' => module_exists('entitycache'),
` appears both for `og_membership_type` and for `og_membership`.

This is problematic as the entity cache functionality is now part of core (it used to be a contrib module called `entitycache`). So this line will always return false, effectively disabling the entity cache. I don't know if that has to do with some of the issues in these tests. I'll be checking on that too.

**Comment by indigoxela** [comment]
> OgUiUserPermissionsTestCase. I wanted to give that one a try with the original code ... to see if I can make that work ... But I don't want to step on any toes...

You're not stepping on my toes at all, just go for it. Good luck! :crossed_fingers:

> module called entitycache...

Locally I tried all sorts of changes - removing the module_exists() was one of my first steps. Didn't manage to get any values into that db table. May the force be with you!

**Comment by argiepiano** [comment]
Success!!! All tests for `OgUiUserPermissionsTestCase` are now passing. I restored the original code and made a couple of needed modifications:
- First, there was an error in method `EntityClassType::entityType()`
- Second, since the test was creating an `og_entity_test` entity of bundle 'main',  and since this entity type has a bundle definition entity called `og_entity_test_type`, it is necessary to create, first, the 'main' bundle definition, and then create the actual entity.

This second point was not an issue with D7 because the entities that it used were properly handled by `entity_test.module`. That's not the case in Backdrop.

PR #62 .

Please note: #58 will clash with #62 - they both focus on the same code. @indigoxela, if you don't mind, since the tests for `OgUiUserPermissionsTestCase` are now passing, would you mind closing #58 ?

**Comment by argiepiano** [comment]
One more note about #58. The commit [926ab7d](https://github.com/backdrop-contrib/og/pull/58/commits/926ab7d549f8377f9ae4149ef6ee48b7f3878ca6)  that is part of that PR SHOULD be merged (deals with EntityStorageException). The other commit in that PR should not, as #62 actually solved the issues.

Incidentally, @indigoxela, I found why Backdrop OG trows `EntityStorageException` instead of `OgException`. It has to do with the node controller, specifically with [this line](https://github.com/backdrop/backdrop/blob/57bc2e7b22a08a412a5a44e07b7a2fc21fec28e2/core/modules/node/node.entity.inc#L510).

Unlike Entity API's `EntityAPIController`, Backdrop's version for nodes, called `NodeStorageController` recasts the exception to be thrown into `EntityStorageException`  - not sure this is a good idea, but it is in core and it would take a lot of convincing to change it. Since the OgException happens within the node saving process, the exception cascades up until it reaches the lines above, and is recast as EnttiyStorageException. 

SO, I think your solution of using 'or' is the appropriate way to deal with this change.

**Comment by indigoxela** [comment]
> Success!!!

That's fantastic!

> ... since the tests for OgUiUserPermissionsTestCase are now passing, would you mind closing #58

Sure, done now.

**Comment by argiepiano** [comment]
PR #65 (linked to issue #56) now allows tests in `OgAccessTestCase` to pass 🎉

**Comment by argiepiano** [comment]
PR #66 fixes `OgAccessUseGroupDefaultsTestCase`.

This fix was originally provided by @indigoxela in #58, which was closed and not merged. Thanks, @indigoxela!

**Comment by argiepiano** [comment]
PR #68 "fixes" `OgEntityFieldQueryTestCase` - with a caveat: I had to change how we test EFQs for entities with multiple OG audience fields. See #67 for an explanation. PR #68, linked to that issue.

**Comment by argiepiano** [comment]
PR #70 fixes `OgNonMembersPublishingContentTestCase`. I ported Entityreference Prepopulate, which was needed for this test, and it now passes successfully.

[EDIT] It looks like GHA is not picking the newly released Entityreference Prepopulate module, and so the test failed. I'm trigger it again.

[EDIT2] GHA is still not finding the new release. I'll re-trigger tomorrow.

**Comment by argiepiano** [comment]
PR #71 fixes `OgGroupAndUngroup`. 

IMPORTANT NOTE: GHA says it's still failing. This is because PR #64 MUST be merged before this PR has an effect.

**Comment by argiepiano** [comment]
`OgRoleRevoke` is also fixed by #64! 🎉  (which needs to be merged)
