### ISSUE TITLE
Upgrade path

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/og#6]
We'll need to assure an upgrade path from Drupal 7 before a formal release.

**Comment by argiepiano** [comment]
Anybody willing to test the D7 upgrade with OG? This is an important step before a beta release. @stpaultim? @olafgrabienski?

**Comment by olafgrabienski** [comment]
> Anybody willing to test the D7 upgrade with OG?

Sure, I will try an upgrade (probably next week).

**Comment by argiepiano** [comment]
I've done some "mid grade" testing with D7 upgrades. Everything is working very well 🎉 . My testing included groups with different visibility, postings with different visibility, and users with different levels of access. Both versions D7 and Backdrop are behaving in the same way 👍🏽 

I also included some custom views (e.g. views that use OG context to show all posts in the group being viewed). All good! 

Please check #117 for an important caveat (re: stub entity_plus module).

@olafgrabienski, if you could do some additional testing that'd be great.

**Comment by olafgrabienski** [comment]
@argiepiano Today I've also upgraded a D7 test site with Organic Groups to Backdrop. It **worked like a charm**, with one exception, but I guess that's only a documentation issue:

After the updrade, I wasn't able to access the People list of a group, e.g. `group/node/1/admin/people`. Got the following error instead:

> Call to a member function set_arguments() on bool in og_ui_admin_account() (line 466 of /.../modules/og-1.x-2.x/og_ui/og_ui.admin.inc).

Later, I saw that the "Admin people View" on `admin/config/group/settings` was set to a "file_admin" view. In Drupal it was "og_members_admin". On further inspection, I noticed that none of the OG provided views were available in my Backdrop installation. After rebuilding that view, everything worked as expected. I guess, before doing the upgrade, I should have saved the module-provided views in the database. If my assumption is correct, I'd suggest to add a hint to the README.

**Comment by argiepiano** [comment]
Thanks so much for testing, @olafgrabienski! Yes, the d7 views are "in code" rather than in the database. This is a standard step in d7 to backdrops upgrade: you must move all d7 views to database. The easiest way to do this, as explained in the upgrade directions provided for backdrop, is to open the view, edit anything without changing it, and save the view.. all this before exporting the database. 

We can add this to the og wiki perhaps?

**Comment by argiepiano** [comment]
One thing we could do, though, is to install the default views to config upon upgrade. Currently, the default views provided by og are not installed when upgrading. This is to avoid overwriting any customization done in d7

**Comment by olafgrabienski** [comment]
> Yes, the d7 views are "in code" rather than in the database. This is a standard step in d7 to backdrops upgrade

Yep, I'm generally aware of this step. As I set up a vanilla D7 site with OG, it should have been clear to me that the views were still "in code", but I didn't think about it. Btw, is there a good way to identify all the views of a D7 site which aren't already in the database?

> We can add this to the og wiki perhaps?

Or to https://github.com/backdrop-contrib/og#upgrade-process? (Or maybe move this section to the Wiki and include the views database hint there, still mentioning as important upgrade instructions in the README.)

> One thing we could do, though, is to install the default views to config upon upgrade.

But then we wouldn't avoid overwriting customized views, right?

**Comment by argiepiano** [comment]
@olafgrabienski, I've found that if we run `config_install_default_config('og')` in `og_update_1000()`, this will install the default views. The cool thing is that this will not overwrite any existing views. Since `views_update_1000()` (which moves views from database to config) runs BEFORE `og_update_1000()`, as Views is in core this prevents the risk of overwriting any overridden OG views coming from D7 database. 

So, we can safely install those default views. I'll do a PR for that.

@laryn, if you have any concerns about this (installing the default views when upgrading), let me know please.

**Comment by argiepiano** [comment]
Check #120 and corresponding PR that installs the default views without overwriting any overridden ones from D7.

**Comment by olafgrabienski** [comment]
@argiepiano As you and me have both made some test upgrades, and you provided the default views in #120, should we close this issue?

**Comment by argiepiano** [comment]
Agreed! Closing this.
