### ISSUE TITLE
Enhancement: summary in Organic Groups vertical tab on a content type

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/og#8]
This doesn't seem to exist in the Drupal 7 version either:
![Screen Shot 2020-11-15 at 7 24 29 AM](https://user-images.githubusercontent.com/871421/99186180-3e1f4d00-2714-11eb-9054-a3fd37fa4da5.jpg)

It would be a nice enhancement to match the rest of the vertical tabs and add in a short summary of any selections that have been made.

**Comment by stpaultim** [comment]
I've noticed this as well. This is the only vertical tab in my test site without any extra information.

**Comment by argiepiano** [comment]
Added in #103. That PR also improves the clarity of the OG vertical tab settings, and disallows selecting a Target Type and Target Bundles if they have been selected previously for the "Group Audience" default field. 

@laryn, if you have a chance, it'd be great to have you test the new summary and functionality.

I will close this issue, since it's been addressed there.
