### ISSUE TITLE
Fix the actions of the membership list

### ISSUE THREAD

**Issue by VasasA** [backdrop-contrib/og#85]
The converted [Views Bulk Operations](https://backdropcms.org/project/views_bulk_operations) module provides an opportunity to fix the actions.
I will create a PR, that will fix the actions of the membership list in the `1.x-2.x-issue-22` [branch](https://github.com/backdrop-contrib/og/tree/1.x-2.x-issue-22).
After the merging of PR, the `1.x-2.x-issue-22` branch needs merge into the main branch.

**Comment by argiepiano** [comment]
@VasasA, there is already a PR for #22 which I submitted. We had some discussion as well. @olafgrabienski thought it'd be best not to have to depend on VBO for these Bulk Operations. My PR uses core's Bulk Operation API.

BTW, I ported VBO, but I think since the use in OG is so minimal, we might as well stick to the core API and not depend on VBO.

**Comment by VasasA** [comment]
Your solution is very good, thank you! :+1: 
(I close this issue.)

**Comment by argiepiano** [comment]
Thanks @VasasA. It seems like my fix was tested and works - I'm not sure who needs to merge this. I'm not a maintainer. I think @laryn is (he's busy with the 1.22.0 release), not sure about @olafgrabienski. Are you a maintainer?

**Comment by VasasA** [comment]
@laryn has written in the README.md: "Co-maintainers and collaborators are welcome." 
I'm not maintainer, I don't use this module. Sorry!

**Comment by olafgrabienski** [comment]
> not sure about olafgrabienski

No, I'm not a maintainer, not enough skills / capacities (but still happy to help with testing).
