### ISSUE TITLE
The self test needs the Entity reference prepopulate module

### ISSUE THREAD

**Issue by VasasA** [backdrop-contrib/og#98]
The "OG non members publishing" self test (admin/config/development/testing) uses the Entity reference prepopulate module, but it isn't a dependency module in the `og.info`. The test works if you put the prepopulate module in the `modules` directory. Should we mention this in the README.md?
In the `og.test`:
```php
    $modules[] = 'entityreference_prepopulate';
    parent::setUp($modules);
```

**Comment by argiepiano** [comment]
Hmmm... I'm not sure this is necessary. Automated tests are there to be run in the GHA environment. The GHA script automatically installs all dependencies needed for the test. Since 99% of users of OG won't be concerned about running an automated test, I would think that including this info in the readme is not needed - while it won't hurt, it may confuse users not familiar with automated tests.

If anything, we could add a comment to the test prompting developers interested in running the test locally to put that module in the modules folder.

@laryn, what do you think?

**Comment by VasasA** [comment]
We could complete the description of the test in the `og.tests.info`:
```
name = OG non members publishing
description = Grant access to non members users publishing content with the group passed in the query string. <a href="https://backdropcms.org/project/entityreference_prepopulate/">Entity reference prepopulate module</a> is required!
```

**Comment by argiepiano** [comment]
Sounds like a great idea. Care to prepare a PR?

**Comment by VasasA** [comment]
I done it :+1: 
I was happy to help. :smile:

**Comment by argiepiano** [comment]
Thank you, @VasasA!
